---
- name: create cloudflare DNS records
  cloudflare_dns:
    zone: "{{ pd_cloudflare_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    # 1 is auto
    ttl: 1
    type: A
    value: "{{ pd_public_ip }}"
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "cloudflare" 

- name: Create DNS record at Route53
  route53:
    state: present
    zone: "{{ pd_aws_zone }}"
    record: "{{ item }}.{{ pd_public_domain }}"
    type: A
    ttl: 120
    value: "{{ pd_public_ip }}"
    wait: yes
    aws_access_key: "{{ pd_aws_access_key }}"
    aws_secret_key: "{{ pd_aws_secret_key }}"
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "route53" 

- name: Create DNS record at GCP 
  gcp_dns_resource_record_set:
    name: "{{ item }}.{{ pd_public_domain }}." 
    managed_zone: 
        name: "{{ gcp_managed_zone_name }}"
        dnsName: "{{ gcp_managed_zone_domain }}"
    type: A
    ttl: 120
    target:
    - "{{ pd_public_ip }}" 
    project: "{{ gcp_project }}"
    auth_kind: serviceaccount
    service_account_file: "{{ gcp_serviceaccount_file }}"
    state: present
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "gcp"

- name: Create DNS zone at Azure
  azure_rm_dnszone:
    resource_group: "{{ azure_rg }}"
    name: "{{ pd_public_domain }}"
    state: present
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    tenant: "{{ azure_tenant }}"
  register: az_nameservers
  when: pd_provider == "azure"
  delegate_to: localhost

- name: Debug DNS ns records at Azure
  debug:
    msg: "{{ az_nameservers.state.name_servers }}"

- name: Create DNS ns records dict entries at Azure
  set_fact:
    az_ns_entries: "{{ az_ns_entries | default([]) + [{ 'entry' : item }] }}"
  loop: "{{ az_nameservers.state.name_servers }}"

- name: Debug DNS ns records at Azure
  debug:
    msg: "{{ az_ns_entries }}"

- name: Create DNS ns records at Azure
  azure_rm_dnsrecordset:
    resource_group: "{{ azure_rg }}"
    relative_name: "{{ cluster_name }}"
    zone_name: "{{ public_domain }}"
    record_type: NS
    records: "{{ az_ns_entries }}"
    state: present
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    tenant: "{{ azure_tenant }}"
  when: pd_provider == "azure"
  delegate_to: localhost

- name: Create DNS record at Azure
  azure_rm_dnsrecordset:
    resource_group: "{{ azure_rg }}"
    relative_name: "{{ item }}"
    zone_name: "{{ pd_public_domain }}"
    record_type: A
    time_to_live: 120
    records:
    - entry: "{{ pd_public_ip }}" 
    state: present
    subscription_id: "{{ azure_subscription_id }}"
    client_id: "{{ azure_client_id }}"
    secret: "{{ azure_secret }}"
    tenant: "{{ azure_tenant }}"
  with_items:
  - api
  - '*.apps'
  when: pd_provider == "azure"
  delegate_to: localhost
