---
- name: Enable required repository
  rhsm_repository:
    name: cnv-2.2-for-rhel-8-x86_64-rpms
    state: enabled
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"

- name: Enable required repository
  rhsm_repository:
    name: rhel-7-server-cnv-2.2-rpms
    state: enabled
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "7"

- name: Installing virtctl Packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - kubevirt-virtctl
    - qemu-img
